global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "minecraft"
    static_configs:
      - targets: ["minecraft:9940"]
        labels:
          server_name: "local-test"

      - targets: ["mc1:9940"]
        labels:
          server_name: "mc1"

      - targets: ["mc2:9940"]
        labels:
          server_name: "mc2"

      - targets: ["mc3:9940"]
        labels:
          server_name: "mc3"

      - targets: ["mc4:9940"]
        labels:
          server_name: "mc4"

      - targets: ["mc5:9940"]
        labels:
          server_name: "mc5"

      - targets: ["2.56.99.112:9941"]
        labels:
          server_name: "soft-mc1"

      - targets: ["2.56.99.112:9942"]
        labels:
          server_name: "soft-mc2"

      - targets: ["2.56.99.112:9943"]
        labels:
          server_name: "soft-mc3"

      - targets: ["2.56.99.112:9944"]
        labels:
          server_name: "soft-mc4"

      - targets: ["2.56.99.112:9945"]
        labels:
          server_name: "soft-mc5"
