global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "minecraft"
    static_configs:
      - targets: ["185.170.113.136:9941"]
        labels:
          server_name: "mm-mc1"

      - targets: ["185.170.113.136:9942"]
        labels:
          server_name: "mm-mc2"

      - targets: ["185.170.113.136:9943"]
        labels:
          server_name: "mm-mc3"

      - targets: ["185.170.113.136:9944"]
        labels:
          server_name: "mm-mc4"

      - targets: ["185.170.113.136:9945"]
        labels:
          server_name: "mm-mc5"

      - targets: ["2.56.99.112:9941"]
        labels:
          server_name: "nc3-mc1"

      - targets: ["2.56.99.112:9942"]
        labels:
          server_name: "nc3-mc2"

      - targets: ["2.56.99.112:9943"]
        labels:
          server_name: "nc3-mc3"

      - targets: ["2.56.99.112:9944"]
        labels:
          server_name: "nc3-mc4"

      - targets: ["2.56.99.112:9945"]
        labels:
          server_name: "nc3-mc5"
